remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [tck_dsol_v2_0]
description: [Jakarta EE Technology Compatibility Kit User's Guide for Jakarta Debugging Upport for Other Languages (DSOL), Release 2.0]

# sidebar links url
links:
  source: https://github.com/eclipse-ee4j/jsp-api
  download: https://github.com/eclipse-ee4j/jsp-api/releases
  #mailinglist: https://javaee.groups.io/g/tck_dsol_v2_0
  #javadocs:
  docs: https://jakarta.ee/specifications/debugging/2.0
  #faq:
